services:
  todo-playground-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: todo-playground-server
    container_name: todo-playground-server
    # restart: always, on-failure, unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - ../.env
    volumes:
      - ./../src:/usr/src/app/src
      - ./../.env:/usr/src/app/env
    depends_on:
      - mongo
      - redis-db
    networks:
      - nestjs-todo-network

  mongo:
    image: mongo
    container_name: todo-playground-mongo
    restart: always
    ports:
      - '27016:27017'
    networks:
      - nestjs-todo-network

  redis-db:
    image: redis
    container_name: todo-playground-redis
    ports:
      - '6378:6379'
    networks:
      - nestjs-todo-network

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - nestjs-todo-network
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - nestjs-todo-network
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - nestjs-todo-network

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  nestjs-todo-network:
